# -*- coding: utf-8 -*-
"""CSE447_Lab7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouYD5AP9vWlHlffcj2lq3vHyJfxAwb8o

**Consider the elliptic curve E: 𝑦2  = 𝑥3 − 2𝑥 + 2 (mod 23) and P = (4, 9)**

1. Calculate the value of 2P and 3P.

2. Suppose this E and P = (4, 9) are used in an ECC Diffie-Hellman key exchange, where Alice chooses the secret value a = 3 and Bob chooses the secret value b = 6. What is the shared key among Alice and Bob?
"""

# Elliptic curve: y^2 = x^3 - 2x + 2 (mod 23)
p = 23
a = -2
b = 2
P = (4, 9)

def inverse_mod(k, p):
    return pow(k, -1, p)

#implement ECC point addition (also handle doubling)
def point_add(P, Q, a, p):
    if P is None:
        return Q
    if Q is None:
        return P
    if P[0] == Q[0] and (P[1] == -Q[1]):
        return None
    if P == Q:
        m = (3 * P[0]**2 + a) * inverse_mod(2 * P[1], p)
    else:
        m = (Q[1] - P[1]) * inverse_mod(Q[0] - P[0], p)
    x_r = (m**2 - P[0] - Q[0]) % p
    y_r = (m * (P[0] - x_r) - P[1]) % p
    return (x_r, y_r)

#implement double-and-add scalar multiplication
def scalar_mult(k, P, a, p):

    #start with R as None (point at infinity)
    R = None
    #loop while k > 0, check k's binary bits
    while k > 0:
        if k % 2 == 1:
            R = point_add(R, P, a, p)
        P = point_add(P, P, a, p)
        k = k >> 1
    return R

# 1) 2P and 3P
P2 = scalar_mult(2, P, a, p)
P3 = scalar_mult(3, P, a, p)
print("2P =", P2)
print("3P =", P3)

# 2) ECC Diffie–Hellman
a_secret = 3
b_secret = 6

A_pub = scalar_mult(a_secret, P, a, p)
B_pub = scalar_mult(b_secret, P, a, p)

shared_A = scalar_mult(a_secret, B_pub, a, p)
shared_B = scalar_mult(b_secret, A_pub, a, p)

print("Alice's public key:", A_pub)
print("Bob's public key:", B_pub)
print("Shared key (Alice):", shared_A)
print("Shared key (Bob):", shared_B)